[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MesloLGM Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGM Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
